kind: pipeline
type: docker
name: session-integration-tests

steps:
- name: playwright tests
  image: mcr.microsoft.com/playwright:v1.37.0-jammy
  environment:
    NVM_DIR: /usr/local/nvm
    NODE_VERSION: 18.15.0
    SESSION_DESKTOP_ROOT: /root/session-desktop
    NODE_PATH: $NVM_DIR/v$NODE_VERSION/lib/node_modules
    SESSION_BRANCH: unstable
    TESTS_BRANCH: main

  commands:
  - export PATH=$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

  - apt update
  - apt install -y cmake build-essential time
  - mkdir -p $NVM_DIR
  - git config --global --add safe.directory $SESSION_DESKTOP_ROOT
  - git config --global --add safe.directory $DRONE_WORKSPACE
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
  - echo "source $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default" | bash
  - echo "plop $PWD"
  - git clone https://github.com/oxen-io/session-desktop/ -b $SESSION_BRANCH $SESSION_DESKTOP_ROOT
  - cd $SESSION_DESKTOP_ROOT && yarn install --frozen && yarn build-everything
  - cd $DRONE_WORKSPACE && yarn install --frozen && cd -
  - cd $DRONE_WORKSPACE && PLAYWRIGHT_WORKER_COUNT=4 PLAYWRIGHT_RETRIES_COUNT=1 time xvfb-run --auto-servernum yarn test


# kind: pipeline
# type: docker
# name: session-integration-tests

# steps:
# - name: playwright tests
#   image: localhost:5000/session-playwright-jammy
#   commands:
#   - cd $SESSION_DESKTOP_ROOT && yarn install --frozen && yarn build-everything
#   - cd $DRONE_WORKSPACE && yarn install --frozen && cd -